wwo-proxy:
  image: wkicior/wwo-proxy
  ports:
    - "8000:80"
mail-gateway:
  image: wkicior/mail-gateway
  ports:
    - "9998:81"
  privileged: true
  volumes:
    - ../mail-gateway:/app:rw
notifications-mongo:
  image: mongo
notifications-service:
  image: wkicior/notifications-service
  ports:
    - "9999:80"
  links:
    - mail-gateway
    - notifications-mongo
  privileged: true
  volumes:
    - ../notifications-service:/app:rw
forecast-engine:
  image: wkicior/forecast-engine
  ports:
    - "8091:8020"
  links:
    - notifications-service
    - wwo-proxy
  privileged: true
  volumes:
    - ~/.m2:/root/.m2
